################################################################################
# Node-RED Stack or Compose
################################################################################
# docker stack deploy node-red --compose-file docker-compose-node-red.yml
# docker-compose -f docker-compose-node-red.yml -p myNoderedProject up
################################################################################
version: "3.7"

services:
  vflow:
    image: vioneta/vflow:latest-debian
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    networks:
      - vflow-net
    volumes:
      - data:/data

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data

networks:
  vflow-net:
